import { eq } from 'drizzle-orm';
import { config } from '../config.js';
import { db } from '../db/client.js';
import { eggTypes, twitchUserTokens, users } from '../db/schema.js';
export type TwitchReward = { id: string; title: string; cost: number; prompt: string; background_color: string; is_global_cooldown_enabled: boolean; global_cooldown_seconds: number; is_max_per_stream_enabled: boolean; max_per_stream: number; is_max_per_user_per_stream_enabled: boolean; max_per_user_per_stream: number; };
const REWARD_PREFIX = '[Erwin Hatchery]';
const rewardTitleForEgg = (n: string): string => `${REWARD_PREFIX} ${n}`.slice(0, 45);
const rewardPromptForEgg = (id: string): string => `Automatisch verwaltet. Ei-Typ: ${id}`.slice(0, 200);
function rewardCostForEggType(id: string): number { if (id.includes('rare')) return 5000; if (id.includes('uncommon')) return 2500; return 1000; }
type EggTypeRewardConfig = { id: string; displayName: string; twitchRewardId: string | null; twitchRewardTitle: string | null; twitchRewardPrompt: string | null; twitchRewardCost: number | null; twitchRewardBackgroundColor: string | null; twitchRewardGlobalCooldownMinutes: number | null; twitchRewardMaxPerStream: number | null; twitchRewardMaxPerUserPerStream: number | null; isActive: boolean; };
function rewardConfigForEggType(eggType: EggTypeRewardConfig) { const title = (eggType.twitchRewardTitle?.trim() || rewardTitleForEgg(eggType.displayName)).slice(0, 45); const prompt = (eggType.twitchRewardPrompt?.trim() || rewardPromptForEgg(eggType.id)).slice(0, 200); const cost = eggType.twitchRewardCost ?? rewardCostForEggType(eggType.id); const backgroundColor = eggType.twitchRewardBackgroundColor?.trim() || '#9147ff'; const cooldownMinutes = Math.max(0, eggType.twitchRewardGlobalCooldownMinutes ?? 0); const maxPerStream = Math.max(0, eggType.twitchRewardMaxPerStream ?? 0); const maxPerUserPerStream = Math.max(0, eggType.twitchRewardMaxPerUserPerStream ?? 0); return { title, prompt, cost, backgroundColor, isGlobalCooldownEnabled: cooldownMinutes > 0, globalCooldownSeconds: cooldownMinutes * 60, isMaxPerStreamEnabled: maxPerStream > 0, maxPerStream, isMaxPerUserPerStreamEnabled: maxPerUserPerStream > 0, maxPerUserPerStream }; }
async function twitchApi<T>(path: string, userToken: string, init?: RequestInit): Promise<T> { const response = await fetch(`https://api.twitch.tv/helix${path}`, { ...init, headers: { 'Client-Id': config.TWITCH_CLIENT_ID, Authorization: `Bearer ${userToken}`, 'Content-Type': 'application/json', ...(init?.headers ?? {}) } }); if (!response.ok) { const details = await response.text(); throw new Error(`Twitch custom reward API failed (${response.status}): ${details.slice(0, 300)}`); } return (await response.json()) as T; }
async function loadToken(){const b=await db.select({ accessToken:twitchUserTokens.accessToken, scope:twitchUserTokens.scope}).from(twitchUserTokens).innerJoin(users,eq(users.id,twitchUserTokens.userId)).where(eq(users.twitchUserId,config.TWITCH_BROADCASTER_ID)).limit(1);const t=b[0]; if(!t?.accessToken) throw new Error('Missing broadcaster OAuth token. Login with broadcaster account first.'); if(!t.scope.includes('channel:manage:redemptions')) throw new Error('Broadcaster token missing scope channel:manage:redemptions. Login again to refresh scopes.'); return t.accessToken;}
export async function listManagedCustomRewards(): Promise<TwitchReward[]> { const token=await loadToken(); const e=await twitchApi<{data:TwitchReward[]}>(`/channel_points/custom_rewards?broadcaster_id=${encodeURIComponent(config.TWITCH_BROADCASTER_ID)}&only_manageable_rewards=true`,token); return e.data; }
export async function syncEggTypeCustomRewards(): Promise<{ created: number; updated: number; removed: number; skipped: number; total: number }> {
 const token=await loadToken();
 const rows=await db.select({id:eggTypes.id,displayName:eggTypes.displayName,twitchRewardId:eggTypes.twitchRewardId,twitchRewardTitle:eggTypes.twitchRewardTitle,twitchRewardPrompt:eggTypes.twitchRewardPrompt,twitchRewardCost:eggTypes.twitchRewardCost,twitchRewardBackgroundColor:eggTypes.twitchRewardBackgroundColor,twitchRewardGlobalCooldownMinutes:eggTypes.twitchRewardGlobalCooldownMinutes,twitchRewardMaxPerStream:eggTypes.twitchRewardMaxPerStream,twitchRewardMaxPerUserPerStream:eggTypes.twitchRewardMaxPerUserPerStream,isActive:eggTypes.isActive}).from(eggTypes);
 const existing=await twitchApi<{data:TwitchReward[]}>(`/channel_points/custom_rewards?broadcaster_id=${encodeURIComponent(config.TWITCH_BROADCASTER_ID)}&only_manageable_rewards=true`,token);
 let created=0,updated=0,removed=0,skipped=0;
 for (const eggType of rows.filter(r=>r.isActive)) { const cfg=rewardConfigForEggType(eggType); const current=existing.data.find(r=>r.id===eggType.twitchRewardId)||existing.data.find(r=>r.title===cfg.title);
 if(!current){ const cr=await twitchApi<{data:TwitchReward[]}>(`/channel_points/custom_rewards?broadcaster_id=${encodeURIComponent(config.TWITCH_BROADCASTER_ID)}`,token,{method:'POST',body:JSON.stringify({title:cfg.title,prompt:cfg.prompt,cost:cfg.cost,background_color:cfg.backgroundColor,is_global_cooldown_enabled:cfg.isGlobalCooldownEnabled,global_cooldown_seconds:cfg.globalCooldownSeconds,is_max_per_stream_enabled:cfg.isMaxPerStreamEnabled,max_per_stream:cfg.maxPerStream,is_max_per_user_per_stream_enabled:cfg.isMaxPerUserPerStreamEnabled,max_per_user_per_stream:cfg.maxPerUserPerStream,is_enabled:true})}); const rid=cr.data[0]?.id; if(rid) await db.update(eggTypes).set({twitchRewardId:rid}).where(eq(eggTypes.id,eggType.id)); created++; continue; }
 const needs=current.cost!==cfg.cost||current.prompt!==cfg.prompt||current.background_color!==cfg.backgroundColor||current.is_global_cooldown_enabled!==cfg.isGlobalCooldownEnabled||current.global_cooldown_seconds!==cfg.globalCooldownSeconds||current.is_max_per_stream_enabled!==cfg.isMaxPerStreamEnabled||current.max_per_stream!==cfg.maxPerStream||current.is_max_per_user_per_stream_enabled!==cfg.isMaxPerUserPerStreamEnabled||current.max_per_user_per_stream!==cfg.maxPerUserPerStream;
 if(needs){ await twitchApi(`/channel_points/custom_rewards?broadcaster_id=${encodeURIComponent(config.TWITCH_BROADCASTER_ID)}&id=${encodeURIComponent(current.id)}`,token,{method:'PATCH',body:JSON.stringify({prompt:cfg.prompt,cost:cfg.cost,background_color:cfg.backgroundColor,is_global_cooldown_enabled:cfg.isGlobalCooldownEnabled,global_cooldown_seconds:cfg.globalCooldownSeconds,is_max_per_stream_enabled:cfg.isMaxPerStreamEnabled,max_per_stream:cfg.maxPerStream,is_max_per_user_per_stream_enabled:cfg.isMaxPerUserPerStreamEnabled,max_per_user_per_stream:cfg.maxPerUserPerStream,is_enabled:true})}); updated++; } else skipped++;
 await db.update(eggTypes).set({twitchRewardId:current.id}).where(eq(eggTypes.id,eggType.id)); }
 for (const eggType of rows.filter(r=>!r.isActive && r.twitchRewardId)) { const rewardId = eggType.twitchRewardId; if (!rewardId) continue; try { await twitchApi(`/channel_points/custom_rewards?broadcaster_id=${encodeURIComponent(config.TWITCH_BROADCASTER_ID)}&id=${encodeURIComponent(rewardId)}`,token,{method:'DELETE'});} catch { skipped++; } await db.update(eggTypes).set({twitchRewardId:null}).where(eq(eggTypes.id,eggType.id)); removed++; }
 return {created,updated,removed,skipped,total:rows.length};
}
